server:
  port: 8050


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    driver-class-name: org.postgresql.Driver
    username: alibou
    password: alibou
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgesql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8762}/eureka/
    register-with-eureka: true
    fetch-registry: true









