#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#  application:
#    name: discovery
#server:
#  port: 8762

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: discovery















